### ISSUE TITLE
Installation issue on osx 

### ISSUE THREAD

**Issue by Henrilin28** [clementfarabet/gfx.js#3] opened 2014-04-16 16:05 UTC
$ luajit -lgfx.start
luajit: /usr/local/share/lua/5.1/graphicsmagick/Image.lua:179: dlopen(libGraphicsMagickWand.dylib, 5): Library not loaded: /usr/local/lib/libpng15.15.dylib
  Referenced from: /usr/local/lib/libGraphicsMagickWand.dylib
  Reason: image not found
stack traceback:
    [C]: in function 'load'
    /usr/local/share/lua/5.1/graphicsmagick/Image.lua:179: in main chunk
    [C]: in function 'require'
    /usr/local/share/lua/5.1/graphicsmagick/init.lua:2: in main chunk
    [C]: in function 'require'
    /usr/local/share/lua/5.1/gfx/js.lua:9: in main chunk
    [C]: in function 'require'
    /usr/local/share/lua/5.1/gfx/start.lua:6: in main chunk
    [C]: at 0x010e077280
    [C]: at 0x010e04ac50
When I try to execute the command and it shows the error above. I have no idea to fix it. Can anyone help me ? I will be really appreciated.

**Comment by soumith** [comment] 2014-04-16 16:07
reinstall libgraphicsmagickwand. looks like it was compiled with libpng15.15 but libpng was updated and cleaned up ("brew cleanup" possibly), but libgraphicsmagickwand is still looking for the old version.

this is not a bug with gfx.js, so you can close the issue.

**Closed as completed** 2014-04-16 16:08 UTC

**Comment by Henrilin28** [comment] 2014-04-16 16:10
Thank you and I closed the issue immediately
